seed: 42
task: train
log_dir: /mnt/data/quant/qlib/examples/log/example/OPDT/
buffer_size: 80000
train_start_date: "2018-09-18"
train_end_date: "2021-06-30"
valid_start_date: "2021-07-01"
valid_end_date: "2022-07-04"
test_start_date: "2021-07-01"
test_end_date: "2022-07-04"
instruments: "csi_nost_20_300y"
day_data_cache_dir: /mnt/data/quant/qlib/data/day_data_cache_dir/
min_data_dir: /mnt/stockdata/eastmoney_min_data
stock_trade_dates: /mnt/dev/HIST/stock_trade_date.json
n_days: 2
io_conf:
  test_sampler: JueTestSampler
  train_sampler: JueSampler
  test_logger: DFLogger
resources:
  num_cpus: 24
  num_gpus: 1
  device: cuda
train_paths:
  raw_dir: /mnt/data/quant/qlib/data/backtest/
  order_dir: /mnt/data/quant/qlib/data/order/train/
  train_start_date: "2018-09-18"
  train_end_date: "2021-06-30"
  valid_start_date: "2021-07-01"
  valid_end_date: "2022-07-04"
  test_start_date: "2021-07-01"
  test_end_date: "2022-07-04"
  instruments: "csi_nost_20_300y"
  day_data_cache_dir: /mnt/data/quant/qlib/data/day_data_cache_dir/
  min_data_dir: /mnt/stockdata/eastmoney_min_data
  stock_trade_dates: /mnt/dev/HIST/stock_trade_date.json
  n_days: 2

valid_paths:
  raw_dir: /mnt/data/quant/qlib/data/backtest/
  order_dir: /mnt/data/quant/qlib/data/order/valid/
  train_start_date: "2018-09-18"
  train_end_date: "2021-06-30"
  valid_start_date: "2021-07-01"
  valid_end_date: "2022-07-04"
  test_start_date: "2021-07-01"
  test_end_date: "2022-07-04"
  instruments: "csi_nost_20_300y"
  day_data_cache_dir: /mnt/data/quant/qlib/data/day_data_cache_dir/
  min_data_dir: /mnt/stockdata/eastmoney_min_data
  stock_trade_dates: /mnt/dev/HIST/stock_trade_date.json
  n_days: 2

test_paths:
  raw_dir: /mnt/data/quant/qlib/data/backtest/
  order_dir: /mnt/data/quant/qlib/data/order/test/
  train_start_date: "2018-09-18"
  train_end_date: "2021-06-30"
  valid_start_date: "2021-07-01"
  valid_end_date: "2022-07-04"
  test_start_date: "2021-07-01"
  test_end_date: "2022-07-04"
  instruments: "csi_nost_20_300y"
  day_data_cache_dir: /mnt/data/quant/qlib/data/day_data_cache_dir/
  min_data_dir: /mnt/stockdata/eastmoney_min_data
  stock_trade_dates: /mnt/dev/HIST/stock_trade_date.json
  n_days: 2

env_conf:
  name: JueStockEnv
  max_step_num: 237
  limit: 10
  time_interval: 30
  interval_num: 8
  features:
  - name: raw
    type: range
    loc: /mnt/data/quant/qlib/data/normed_feature/
    size: 180
  obs:
    name: TeacherObs
    config: {}
  action:
    name: Static_Action
    config:
      action_num: 5
      action_map: [0, 0.25, 0.5, 0.75, 1]
  reward:
    VP_Penalty_small_vec:
      penalty: 100
      coefficient: 1
policy_conf:
  name: PPO
  config:
    discount_factor: 1.
    max_grad_norm: 100.
    reward_normalization: False
    eps_clip: 0.3
    value_clip: True
    vf_coef: 1.
    gae_lambda: 1.
    vf_clip_para: 0.3
network_conf:
  name: Teacher
  config:
    d_feat_day: 7
    d_feat_min: 2
    d_model: 128
    nhead: 4
    num_layers: 2
    dropout: 0.2
    out_shape: 5
    fc_size: 128
optim:
  lr: 1e-4
  batch_size: 64
  max_epoch: 30
  step_per_epoch: 10
  collect_per_step: 10000
  repeat_per_collect: 5
  early_stopping: 5
  weight_decay: 0.